// <auto-generated/> - StyleCop hack to not enforce enum value commentation in this file.
namespace Merchello.Core.Sync
{
    /// <summary>
    /// The message type to be used for syncing across servers.
    /// </summary>
    public enum MessageType
    {
        RefreshAll,
        RefreshByKey,
        RefreshByJson,
        RemoveByKey,
        RefreshByInstance,
        RemoveByInstance,
        RefreshByPayload
    }
}