[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Merchello.Web")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Merchello.Web.UI")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Merchello.Tests.Base")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Merchello.Tests.UnitTests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Merchello.Tests.IntegrationTests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Merchello.Tests.Plugin.TestHelpers")]
