//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

<<<<<<< HEAD
[assembly: AssemblyVersion("2.1.*")]
[assembly: AssemblyInformationalVersion("2.1.0")]
=======
[assembly: AssemblyVersion("2.0.*")]
[assembly: AssemblyInformationalVersion("2.0.1")]
>>>>>>> patch-v-2.0.1


