[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Merchello.Solo")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Merchello.Umbraco")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Merchello.Tests.Base")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Merchello.Tests.Unit")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Merchello.Tests.Umbraco")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Merchello.Tests.Solo")]
