[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Merchello.Web")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Merchello.Umbraco")]
////[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Merchello.Web.Store")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Merchello.Providers")]
////[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Merchello.Tests.Base")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Merchello.Tests.Unit")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Merchello.Tests.Integration.Umbraco")]
////[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Merchello.Tests.Plugin.TestHelpers")]