[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Merchello.Examine")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Merchello.Web")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Merchello.Implementation")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Merchello.UaaS")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Merchello.Providers")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Merchello.Tests.Base")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Merchello.Tests.UnitTests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Merchello.Tests.IntegrationTests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Merchello.Tests.Plugin.TestHelpers")]
// Required for the installer
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Merchello.Bazaar")]