// <auto-generated/> - StyleCop hack to not enforce enum value commentation in this file.
namespace Merchello.Core.Models.Querying
{
    internal enum FieldMatchCondition
    {
        Exact,
        StartsWith,
        EndsWith,
        Wildcard
    }
}