namespace Merchello.Core.Configuration.Sections
{
    /// <summary>
    /// Represents a configuration section for configurations related to Merchello "views" and partial "views" locations. 
    /// </summary>
    public interface IViewsSection : IMerchelloSection
    {
        /// <summary>
        /// Gets the base path for views generated by Merchello.
        /// </summary>
        string DefaultPath { get; }

        /// <summary>
        /// Gets the notification template base path.
        /// </summary>
        string Notifications { get; }
    }
}