// <auto-generated/> - StyleCop hack to not enforce commentation errors in this file.
namespace Merchello.Core
{
    using Merchello.Core.Models;

    /// <summary>
    /// Extension methods for <see cref="ICountry"/>.
    /// </summary>
    public static partial class Extensions
    {
    }
}