// <auto-generated/> - StyleCop hack to not enforce commentation errors in this file.
namespace Merchello.Core
{
    using System;
    using System.Linq;

    using Merchello.Core.Configuration;
    using Merchello.Core.Logging;
    using Merchello.Core.Models;
    using Merchello.Core.Strategies.Itemization;

    /// <summary>
    /// Extension methods for <see cref="InvoiceItemItemization"/>.
    /// </summary>
    public static partial class Extensions
    {
        /// <summary>
        /// Itemizes the items in an invoice.
        /// </summary>
        /// <param name="invoice">
        /// The invoice.
        /// </param>
        /// <returns>
        /// The <see cref="InvoiceItemItemization"/>.
        /// </returns>
        /// <exception cref="Exception">
        /// Throws an exception if the itemization strategy could not be instantiated.
        /// </exception>
        public static InvoiceItemItemization ItemizeItems(this IInvoice invoice)
        {
            var type = MerchelloConfiguration.Current.GetStrategyElement(Constants.StrategyTypeAlias.InvoiceItemizationStrategy).Type;

            var ctrArgValues = new object[] { invoice };

            var strategy = ActivatorHelper.CreateInstance<InvoiceItemizationStrategyBase>(type, ctrArgValues);


            if (strategy.Success)
            {
                return strategy.Result.Itemize();
            }


            MultiLogHelper.Error(typeof(Extensions), "Failed to instantiate the InvoiceItemizationStrategy.", strategy.Exception);

            throw strategy.Exception;
        }


        /// <summary>
        /// Calculates the product total.
        /// </summary>
        /// <param name="itemization">
        /// The itemization.
        /// </param>
        /// <returns>
        /// The <see cref="decimal"/>.
        /// </returns>
        public static decimal CalculateProductTotal(this InvoiceItemItemization itemization)
        {
            return Ensure2Places(itemization.Products.Sum(x => x.Price * x.Quantity));
        }

        /// <summary>
        /// Calculates the  shipping total.
        /// </summary>
        /// <param name="itemization">
        /// The itemization.
        /// </param>
        /// <returns>
        /// The <see cref="decimal"/>.
        /// </returns>
        public static decimal CalculateShippingTotal(this InvoiceItemItemization itemization)
        {
            return Ensure2Places(itemization.Shipping.Sum(x => x.Price * x.Quantity));
        }

        /// <summary>
        /// Calculates the tax total.
        /// </summary>
        /// <param name="itemization">
        /// The itemization.
        /// </param>
        /// <returns>
        /// The <see cref="decimal"/>.
        /// </returns>
        public static decimal CalculateTaxTotal(this InvoiceItemItemization itemization)
        {
            return Ensure2Places(itemization.Tax.Sum(x => x.Price * x.Quantity));
        }

        /// <summary>
        /// Calculates the adjustment total.
        /// </summary>
        /// <param name="itemization">
        /// The itemization.
        /// </param>
        /// <returns>
        /// The <see cref="decimal"/>.
        /// </returns>
        public static decimal CalculateAdjustmentTotal(this InvoiceItemItemization itemization)
        {
            return Ensure2Places(itemization.Adjustments.Sum(x => x.Price * x.Quantity));
        }

        /// <summary>
        /// Calculates the discount total.
        /// </summary>
        /// <param name="itemization">
        /// The itemization.
        /// </param>
        /// <returns>
        /// The <see cref="decimal"/>.
        /// </returns>
        public static decimal CalculateDiscountTotal(this InvoiceItemItemization itemization)
        {
            return Ensure2Places(itemization.Discounts.Sum(x => x.Price * x.Quantity));
        }

        /// <summary>
        /// Calculates the custom total.
        /// </summary>
        /// <param name="itemization">
        /// The itemization.
        /// </param>
        /// <returns>
        /// The <see cref="decimal"/>.
        /// </returns>
        public static decimal CalculateCustomTotal(this InvoiceItemItemization itemization)
        {
            return Ensure2Places(itemization.Custom.Sum(x => x.Price * x.Quantity));
        }

        /// <summary>
        /// Calculates the invoice item total.
        /// </summary>
        /// <param name="itemization">
        /// The itemization.
        /// </param>
        /// <returns>
        /// The total.
        /// </returns>
        public static decimal CalculateTotal(this InvoiceItemItemization itemization)
        {
            var productTotal = itemization.CalculateProductTotal();
            var shippingTotal = itemization.CalculateShippingTotal();
            var taxTotal = itemization.CalculateTaxTotal();
            var adjTotal = itemization.CalculateAdjustmentTotal();
            var discountsTotal = itemization.CalculateDiscountTotal();
            var customTotal = itemization.CalculateCustomTotal();

            return productTotal + shippingTotal + taxTotal + customTotal + adjTotal - discountsTotal;
        }
    }
}
