// <auto-generated/> - StyleCop hack to not enforce enum value commentation in this file.
namespace Merchello.Core
{
    using System;
    using System.Linq;
    using System.Text.RegularExpressions;

    using Merchello.Core.Configuration;
    using Merchello.Core.Models;

    internal static class SkuHelper
    {

        public static string GenerateSkuForVariant(IProduct product, IProductVariant variant)
        {
            var attributes = variant.Attributes.ToProductAttributeCollection();

            return GenerateSkuForVariant(product, variant, attributes);
        }

        public static string GenerateSkuForVariant(
            IProduct product,
            IProductVariant variant,
            ProductAttributeCollection attributes)
        {
            var skuSeparator = MerchelloConfiguration.Current.DefaultSkuSeparator;
            // verify the order of the attributes so that a sku can be constructed in the same order as the UI
            var optionIds = product.ProductOptionsForAttributes(attributes).OrderBy(x => x.SortOrder).Select(x => x.Key).Distinct();

            // the base sku
            var sku = product.Sku;
            // ReSharper disable once UseStringInterpolation
            var name = string.Format("{0} - ", product.Name);

            foreach (var att in optionIds.Select(key => attributes.FirstOrDefault(x => x.OptionKey == key)).Where(att => att != null))
            {
                name += att.Name + " ";

                sku += skuSeparator + (string.IsNullOrEmpty(att.Sku) ? Regex.Replace(att.Name, "[^0-9a-zA-Z]+", string.Empty) : att.Sku);
            }


            return sku;
        }
    }
}