// <auto-generated/> - StyleCop hack to not enforce enum value commentation in this file.
namespace Merchello.Solo.Logging
{
    /// <summary>
    /// Borrowed from https://github.com/cjbhaines/Log4Net.Async - will reference Nuget packages directly in v8
    /// </summary>
    /// <typeparam name="T"></typeparam>
    /// UMBRACO
    /// REFACTOR-remove when Umbraco V8 is released
    internal interface IQueue<T>
    {
        void Enqueue(T item);
        bool TryDequeue(out T ret);
    }
}