// <auto-generated/> - StyleCop hack to not enforce enum value commentation in this file.
namespace Merchello.Core.Acquired.Persistence.DatabaseAnnotations
{
    /// <summary>
    /// Enum with the 2 possible Null settings: Null or Not Null
    /// </summary>
    public enum NullSettings
    {
        Null,
        NotNull
    }
}