// <auto-generated/> - StyleCop hack to not enforce enum value commentation in this file.
namespace Merchello.Core.Acquired.Persistence.DatabaseAnnotations
{
    using System;

    /// <summary>
    /// Attribute that represents a reference between two tables/DTOs
    /// </summary>
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Property)]
    internal class ReferencesAttribute : Attribute
    {
        public ReferencesAttribute(Type type)
        {
            this.Type = type;
        }

        /// <summary>
        /// Gets or sets the Type of the referenced DTO/table
        /// </summary>
        public Type Type { get; set; }
    }
}