! function(t, e, i, o) { t.imageMapProShapeDefaults = { id: "spot-0", title: "", type: "spot", x: -1, y: -1, width: 44, height: 44, actions: { mouseover: "show-tooltip", click: "no-action", link: "#", open_link_in_new_window: 1 }, default_style: { opacity: 1, border_radius: 50, background_color: "#000000", background_opacity: .4, border_width: 0, border_style: "solid", border_color: "#ffffff", border_opacity: 1, fill: "#000000", fill_opacity: .4, stroke_color: "#ffffff", stroke_opacity: .75, stroke_width: 0, stroke_dasharray: "10 10", stroke_linecap: "round", use_icon: 1, icon_type: "library", icon_svg_path: "M409.81,160.113C409.79,71.684,338.136,0,249.725,0C161.276,0,89.583,71.684,89.583,160.113     c0,76.325,119.274,280.238,151.955,334.638c1.72,2.882,4.826,4.641,8.178,4.641c3.351,0,6.468-1.759,8.168-4.631     C290.545,440.361,409.81,236.438,409.81,160.113z M249.716,283.999c-68.303,0-123.915-55.573-123.915-123.895     c0-68.313,55.592-123.895,123.915-123.895s123.876,55.582,123.876,123.895S318.029,283.999,249.716,283.999z", icon_svg_viewbox: "0 0 499.392 499.392", icon_fill: "#000000", icon_url: "", icon_is_pin: 1, icon_shadow: 0 }, mouseover_style: { opacity: 1, border_radius: 50, background_color: "#ffffff", background_opacity: .4, border_width: 0, border_style: "solid", border_color: "#ffffff", border_opacity: 1, fill: "#ffffff", fill_opacity: .4, stroke_color: "#ffffff", stroke_opacity: .75, stroke_width: 0, stroke_dasharray: "10 10", stroke_linecap: "round", icon_fill: "#000000" }, tooltip_style: { border_radius: 5, padding: 20, background_color: "#000000", background_opacity: .9, position: "top", width: 300, auto_width: 0 }, tooltip_content: { content_type: "plain-text", plain_text: "Lorem Ipsum", plain_text_color: "#ffffff", squares_settings: { containers: [{ id: "sq-container-403761", settings: { elements: [{ settings: { name: "Paragraph", iconClass: "fa fa-paragraph" } }] } }] } }, points: [], vs: [] }, t.imageMapProEditorDefaults = { id: 0, editor: { previewMode: 0, selected_shape: -1, tool: "spot", state: { dragging: !1 } }, runtime: { is_fullscreen: 0 }, general: { name: "", shortcode: "", width: 1280, height: 776, naturalWidth: 1280, naturalHeight: 776, responsive: 1, preserve_quality: 1, pageload_animation: "none", late_initialization: 0, center_image_map: 0 }, image: { url: "https://webcraftplugins.com/uploads/image-map-pro/demo.jpg" }, fullscreen: { enable_fullscreen_mode: 0, start_in_fullscreen_mode: 0, fullscreen_background: "#000000", fullscreen_button_position: 1, fullscreen_button_type: "icon_and_text", fullscreen_button_color: "#ffffff", fullscreen_button_text_color: "#222222" }, tooltips: { sticky_tooltips: 0, constrain_tooltips: 1, tooltip_animation: "grow", fullscreen_tooltips: "none" }, spots: [] } }(jQuery, window, document),
function(t, e, i, o) {
    function s(t) { this.settings = t, this.containers = [], this.init() }

    function a(t) { this.settings = t, this.elements = [], this.init() }

    function n(e) { this.settings = e.settings, this.defaults = t.extend(!0, {}, p), this.elementSpecificDefaults = {}, this.options = o, this.init(e) }

    function r(t) { var e = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(t); return e ? { r: parseInt(e[1], 16), g: parseInt(e[2], 16), b: parseInt(e[3], 16) } : null } var l = new Array;
    t.squaresRendererRegisterElement = function(t) { l[t.name] = t }, t.squaresRendererRenderObject = function(t) { if ("object" != typeof t) try { t = JSON.parse(t) } catch (e) { return console.log(e), console.log("Squares renderer failed to parse JSON: "), console.log(t), "" }
        return new s(t).render() }, s.prototype.init = function() { for (var t = 0; t < this.settings.containers.length; t++) this.containers[t] = new a(this.settings.containers[t]) }, s.prototype.render = function() { for (var t = "", e = 0; e < this.containers.length; e++) t += this.containers[e].render(); return t }, a.prototype.init = function() { if (this.settings.settings)
            for (var t = 0; t < this.settings.settings.elements.length; t++) this.elements[t] = new n(this.settings.settings.elements[t]) }, a.prototype.render = function() { var t = ""; if (t += '<div class="squares-container">', this.settings.settings)
            for (var e = 0; e < this.settings.settings.elements.length; e++) t += this.elements[e].render(); return t += '\t<div class="squares-clear"></div>', t += "</div>" }; var p = { layout: { box_model: { margin: { top: 0, bottom: 0, left: 0, right: 0 }, padding: { top: 10, bottom: 10, left: 10, right: 10 } }, use_grid: 1, column_span: { xs: { use: 0, class: "sq-col-xs-12", visible: 0 }, sm: { use: 0, class: "sq-col-sm-12", visible: 0 }, md: { use: 0, class: "sq-col-md-12", visible: 1 }, lg: { use: 1, class: "sq-col-lg-12", visible: 1 } }, width: "100", auto_width: 1, height: "100", auto_height: 1 }, style: { background_color: "#ffffff", background_opacity: "0", opacity: "1", box_shadow: "none", border_width: "0", border_style: "none", border_color: "#000000", border_opacity: "1", border_radius: "0" }, font: { font_family: "sans-serif", font_size: "14", font_weight: "normal", font_style: "normal", line_height: "22", text_color: "#ffffff", text_align: "left", text_decoration: "none", text_transform: "none", text_shadow: "" }, general: { id: "", classes: "", css: "" } };
    n.prototype.init = function(e) { var i = t.extend(!0, {}, l[this.settings.name].controls); for (var o in i) { var s = i[o];
            this.elementSpecificDefaults[o] = {}; for (var a in s) { var n = s[a];
                this.elementSpecificDefaults[o][a] = n.default } } this.defaults = t.extend(!0, {}, this.defaults, this.elementSpecificDefaults), this.options = t.extend(!0, {}, this.defaults, e.options) }, n.prototype.render = function() { var t = ""; return t += '<div class="squares-element ' + this.generateLayoutClass(this.options.layout) + '" style="' + this.generateCSS(this.options) + '">', t += l[this.settings.name].render(this.options), t += "</div>" }, n.prototype.generateLayoutClass = function() { var t = this.options.layout; if (1 == parseInt(t.use_grid, 10)) { var e = "",
                i = t.column_span; return 1 == parseInt(i.xs.use, 10) && (e += i.xs.class + " ", 0 == parseInt(i.xs.visible, 10) && (e += "sq-hidden-xs ")), 1 == parseInt(i.sm.use, 10) && (e += i.sm.class + " ", 0 == parseInt(i.sm.visible, 10) && (e += "sq-hidden-sm ")), 1 == parseInt(i.md.use, 10) && (e += i.md.class + " ", 0 == parseInt(i.md.visible, 10) && (e += "sq-hidden-md ")), 1 == parseInt(i.lg.use, 10) && (e += i.lg.class + " ", 0 == parseInt(i.lg.visible, 10) && (e += "sq-hidden-lg ")), e } return "" }, n.prototype.generateCSS = function() { var t = "",
            e = this.options.layout;
        t += "margin-top: " + e.box_model.margin.top + "px; ", t += "margin-bottom: " + e.box_model.margin.bottom + "px; ", t += "margin-left: " + e.box_model.margin.left + "px; ", t += "margin-right: " + e.box_model.margin.right + "px; ", t += "padding-top: " + e.box_model.padding.top + "px; ", t += "padding-bottom: " + e.box_model.padding.bottom + "px; ", t += "padding-left: " + e.box_model.padding.left + "px; ", t += "padding-right: " + e.box_model.padding.right + "px; ", 1 == parseInt(e.use_grid, 10) || (1 == parseInt(e.auto_width, 10) ? t += "width: auto; " : "" === e.width || isNaN(e.width) || (t += "width: " + e.width + "px; "), 1 == parseInt(e.auto_height, 10) ? t += "height: auto; " : "" === e.height || isNaN(e.height) || (t += "height: " + e.height + "px; ")), t += "float: left; "; var e = this.options.font;
        this.options.fontStyles = "", e && (t += "font-family: " + e.font_family + "; ", this.options.fontStyles += "font-family: " + e.font_family + "; ", t += "font-size: " + e.font_size + "px; ", this.options.fontStyles += "font-size: " + e.font_size + "px; ", t += "font-weight: " + e.font_weight + "; ", this.options.fontStyles += "font-weight: " + e.font_weight + "; ", t += "font-style: " + e.font_style + "; ", this.options.fontStyles += "font-style: " + e.font_style + "; ", t += "line-height: " + e.line_height + "px; ", this.options.fontStyles += "line-height: " + e.line_height + "px; ", t += "color: " + e.text_color + "; ", this.options.fontStyles += "color: " + e.text_color + "; ", t += "text-align: " + e.text_align + "; ", this.options.fontStyles += "text-align: " + e.text_align + "; ", t += "text-decoration: " + e.text_decoration + "; ", this.options.fontStyles += "text-decoration: " + e.text_decoration + "; ", t += "text-transform: " + e.text_transform + "; ", this.options.fontStyles += "text-transform: " + e.text_transform + "; ", t += "text-shadow: " + e.text_shadow + "; ", this.options.fontStyles += "text-shadow: " + e.text_shadow + "; "); var e = this.options.style; if (e) { var i = r(e.background_color);
            t += "background-color: rgba(" + i.r + ", " + i.g + ", " + i.b + ", " + e.background_opacity + "); ", t += "opacity: " + e.opacity + "; ", t += "box-shadow: " + e.box_shadow + "; ", t += "border-width: " + e.border_width + "px; ", t += "border-style: " + e.border_style + "; "; var i = r(e.border_color);
            t += "border-color: rgba(" + i.r + ", " + i.g + ", " + i.b + ", " + e.border_opacity + "); ", t += "border-radius: " + e.border_radius + "px; " } return t } }(jQuery, window, document),
function(t, e, i, o) { var s = { name: "Paragraph", iconClass: "fa fa-paragraph", controls: { text: { text: { name: "Text", type: "textarea", default: "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas." } } }, controlGroupIcons: { text: "fa fa-ellipsis-h" }, content: function() { var t = this.controls.text.text.getVal(); return t = t.replace(/\\(.)/gm, "$1"), t = t.replace(/\n/gm, "<br>"), '<p id="' + this.controls.general.id.getVal() + '" style="' + this.controls.general.css.getVal() + this.fontStyles + ' margin: 0; padding: 0;" class="' + this.controls.general.classes.getVal() + '">' + t + "</p>" }, render: function(t) { var e = t.text.text; return e = e.replace(/\\(.)/gm, "$1"), e = e.replace(/\n/gm, "<br>"), '<p id="' + t.general.id + '" style="' + t.general.css + t.fontStyles + ' margin: 0; padding: 0;" class="' + t.general.classes + '">' + e + "</p>" } };
    t.squaresRegisterElement && t.squaresRegisterElement(s), t.squaresRendererRegisterElement(s); var a = { name: "Heading", iconClass: "fa fa-header", controls: { heading: { text: { name: "Text", type: "text", default: "Lorem Ipsum" }, heading: { name: "Heading", type: "select", options: ["h1", "h2", "h3"], default: "h3" } } }, controlGroupIcons: { heading: "fa fa-header" }, content: function() { return "<" + this.controls.heading.heading.getVal() + ' id="' + this.controls.general.id.getVal() + '" style="' + this.controls.general.css.getVal() + this.fontStyles + ' margin: 0; padding: 0;" class="' + this.controls.general.classes.getVal() + '">' + this.controls.heading.text.getVal() + "</" + this.controls.heading.heading.getVal() + ">" }, render: function(t) { return "<" + t.heading.heading + ' id="' + t.general.id + '" style="' + t.general.css + t.fontStyles + ' margin: 0; padding: 0;" class="' + t.general.classes + '">' + t.heading.text + "</" + t.heading.heading + ">" } };
    t.squaresRegisterElement && t.squaresRegisterElement(a), t.squaresRendererRegisterElement(a); var n = { name: "Image", iconClass: "fa fa-camera", controls: { image: { url: { name: "Image URL", type: "wp media upload", default: "https://webcraftplugins.com/uploads/placeholder_image.png" }, image_is_a_link: { name: "Image is a Link", type: "switch", default: 0 }, link_to: { name: "Link to", type: "text", default: "#" } } }, controlGroupIcons: { image: "fa fa-camera" }, useFontControls: !1, content: function() { var t = ""; return 1 == parseInt(this.controls.image.image_is_a_link.getVal(), 10) && (t += '<a href="' + this.controls.image.link_to.getVal() + '">'), t += '<img src="' + this.controls.image.url.getVal() + '" id="' + this.controls.general.id.getVal() + '" style="' + this.controls.general.css.getVal() + '" class="' + this.controls.general.classes.getVal() + '">', 1 == parseInt(this.controls.image.image_is_a_link.getVal(), 10) && (t += "</a>"), t }, render: function(t) { var e = ""; return 1 == parseInt(t.image.image_is_a_link, 10) && (e += '<a href="' + t.image.link_to + '">'), e += '<img src="' + t.image.url + '" id="' + t.general.id + '" style="' + t.general.css + '" class="' + t.general.classes + '">', 1 == parseInt(t.image.image_is_a_link, 10) && (e += "</a>"), e } };
    t.squaresRegisterElement && t.squaresRegisterElement(n), t.squaresRendererRegisterElement(n); var r = { name: "Video", iconClass: "fa fa-video-camera", controls: { video: { mp4_url: { name: "MP4 URL", type: "text", default: "http://webcraftplugins.com/uploads/example_video.mp4" }, webm_url: { name: "WEBM URL", type: "text", default: "http://webcraftplugins.com/uploads/example_video.webm" }, ogv_url: { name: "OGV URL", type: "text", default: "http://webcraftplugins.com/uploads/example_video.ogv" }, video_is_a_link: { name: "Video is a Link", type: "switch", default: 0 }, link_to: { name: "Link to", type: "text", default: "#" }, autoplay: { name: "Autoplay", type: "switch", default: 0 }, loop: { name: "Loop", type: "switch", default: 0 }, controls: { name: "Controls", type: "switch", default: 0 } } }, useFontControls: !1, controlGroupIcons: { video: "fa fa-video-camera" }, content: function() { var t = "";
            1 == parseInt(this.controls.video.video_is_a_link.getVal(), 10) && (t += '<a href="' + this.controls.video.link_to.getVal() + '">'); var e = ""; return 1 == parseInt(this.controls.video.autoplay.getVal(), 10) && (e += " autoplay "), 1 == parseInt(this.controls.video.loop.getVal(), 10) && (e += " loop "), 1 == parseInt(this.controls.video.controls.getVal(), 10) && (e += " controls "), t += "<video " + e + ' id="' + this.controls.general.id.getVal() + '" style="' + this.controls.general.css.getVal() + '" class="' + this.controls.general.classes.getVal() + '"><source src="' + this.controls.video.mp4_url.getVal() + '" type="video/mp4"><source src="' + this.controls.video.webm_url.getVal() + '" type="video/webm"><source src="' + this.controls.video.ogv_url.getVal() + '" type="video/ogv"></video>', 1 == parseInt(this.controls.video.video_is_a_link.getVal(), 10) && (t += "</a>"), t }, render: function(t) { var e = "";
            1 == parseInt(t.video.video_is_a_link, 10) && (e += '<a href="' + t.video.link_to + '">'); var i = ""; return 1 == parseInt(t.video.autoplay, 10) && (i += " autoplay "), 1 == parseInt(t.video.loop, 10) && (i += " loop "), 1 == parseInt(t.video.controls, 10) && (i += " controls "), e += "<video " + i + ' id="' + t.general.id + '" style="' + t.general.css + '" class="' + t.general.classes + '"><source src="' + t.video.mp4_url + '" type="video/mp4"><source src="' + t.video.webm_url + '" type="video/webm"><source src="' + t.video.ogv_url + '" type="video/ogv"></video>', 1 == parseInt(t.video.video_is_a_link, 10) && (e += "</a>"), e } };
    t.squaresRegisterElement && t.squaresRegisterElement(r), t.squaresRendererRegisterElement(r); var l = { name: "YouTube", iconClass: "fa fa-youtube", useStyleControls: !1, useFontControls: !1, controls: { youtube: { embed_code: { name: "Embed Code", type: "textarea", default: '<iframe width="560" height="315" src="https://www.youtube.com/embed/6NC_ODHu5jg" frameborder="0" allowfullscreen></iframe>' }, allow_fullscreen: { name: "Allow Fullscreen", type: "switch", default: 1 }, iframe_width: { name: "iframe Width", type: "int", default: 320 }, iframe_auto_width: { name: "iframe Auto Width", type: "switch", default: 1 }, iframe_height: { name: "iframe Height", type: "int", default: 320 } } }, controlGroupIcons: { youtube: "fa fa-youtube" }, content: function() { var t = this.controls.youtube.embed_code.getVal(),
                e = ""; return e += '<div id="' + this.controls.general.id.getVal() + '" style="' + this.controls.general.css.getVal() + '" class="' + this.controls.general.classes.getVal() + '">', t = t.replace("allowfullscreen", ""), 1 == parseInt(this.controls.youtube.allow_fullscreen.getVal(), 10) && -1 == t.indexOf("allowfullscreen") && (t = t.replace("></iframe>", " allowfullscreen></iframe>")), t = 1 == parseInt(this.controls.youtube.iframe_auto_width.getVal(), 10) ? t.replace(/width="\d+"/g, 'width="100%"') : t.replace(/width="\d+"/g, 'width="' + this.controls.youtube.iframe_width.getVal() + 'px"'), t = t.replace(/height="\d+"/g, 'height="' + this.controls.youtube.iframe_height.getVal() + 'px"'), e += t, e += "</div>" }, render: function(t) { var e = t.youtube.embed_code,
                i = ""; return i += '<div id="' + t.general.id + '" style="' + t.general.css + '" class="' + t.general.classes + '">', e = e.replace("allowfullscreen", ""), 1 == parseInt(t.youtube.allow_fullscreen, 10) && -1 == e.indexOf("allowfullscreen") && (e = e.replace("></iframe>", " allowfullscreen></iframe>")), e = 1 == parseInt(t.youtube.iframe_auto_width, 10) ? e.replace(/width="\d+"/g, 'width="100%"') : e.replace(/width="\d+"/g, 'width="' + t.youtube.iframe_width + 'px"'), e = e.replace(/height="\d+"/g, 'height="' + t.youtube.iframe_height + 'px"'), i += e, i += "</div>" } };
    t.squaresRegisterElement && t.squaresRegisterElement(l), t.squaresRendererRegisterElement(l); var p = { name: "Button", iconClass: "fa fa-link", controls: { button: { text: { name: "Text", type: "text", default: "Button" }, link_to: { name: "Link to", type: "text", default: "#" }, new_tab: { name: "Open in New Tab", type: "switch", default: 0 }, display: { name: "Display", type: "button group", options: ["inline-block", "block"], default: "inline-block" }, height: { name: "Height", type: "int", default: 44 }, bg_color: { name: "Background Color", type: "color", default: "#2196f3" }, text_color: { name: "Text Color", type: "color", default: "#ffffff" }, border_radius: { name: "Border Radius", type: "int", default: 10 }, padding: { name: "Padding Left/Right", type: "int", default: 20 } } }, controlGroupIcons: { button: "fa fa-link" }, content: function() { var t = "";
            t += "display: " + this.controls.button.display.getVal() + "; ", t += "height: " + this.controls.button.height.getVal() + "px; ", t += "line-height: " + this.controls.button.height.getVal() + "px; ", t += "background-color: " + this.controls.button.bg_color.getVal() + "; ", t += "color: " + this.controls.button.text_color.getVal() + "; ", t += "border-radius: " + this.controls.button.border_radius.getVal() + "px; ", t += "padding-left: " + this.controls.button.padding.getVal() + "px; ", t += "padding-right: " + this.controls.button.padding.getVal() + "px; "; var e = ""; return 1 == parseInt(this.controls.button.new_tab.getVal(), 10) && (e = 'target="_blank"'), '<div id="' + this.controls.general.id.getVal() + '" style="' + this.controls.general.css.getVal() + '" class="' + this.controls.general.classes.getVal() + '"><a href="' + this.controls.button.link_to.getVal() + '" style="' + t + '" ' + e + ' class="squares-button">' + this.controls.button.text.getVal() + "</a></div>" }, render: function(t) { var e = "";
            e += "display: " + t.button.display + "; ", e += "height: " + t.button.height + "px; ", e += "line-height: " + t.button.height + "px; ", e += "background-color: " + t.button.bg_color + "; ", e += "color: " + t.button.text_color + "; ", e += "border-radius: " + t.button.border_radius + "px; ", e += "padding-left: " + t.button.padding + "px; ", e += "padding-right: " + t.button.padding + "px; "; var i = ""; return 1 == parseInt(t.button.new_tab, 10) && (i = 'target="_blank"'), '<div id="' + t.general.id + '" style="' + t.general.css + '" class="' + t.general.classes + '"><a href="' + t.button.link_to + '" style="' + e + '" ' + i + ' class="squares-button">' + t.button.text + "</a></div>" } };
    t.squaresRegisterElement && t.squaresRegisterElement(p), t.squaresRendererRegisterElement(p) }(jQuery, window, document),
function(t, e, i, o) {
    function s(e, i) { this.element = e, this.settings = t.extend(!0, {}, c, i), this.root = t(e), this.wrap = o, this.ui = o, this.shapeContainer = o, this.shapeSvgContainer = o, this.fullscreenTooltipsContainer = o, this.visibleTooltip = o, this.visibleTooltipIndex = o, this.highlightedShape = o, this.highlightedShapeIndex = o, this.clickedShape = o, this.clickedShapeIndex = o, this.bodyOverflow = o, this.initTimeout = o, this.touch = !1, this.fullscreenTooltipVisible = !1, this.init() }

    function a(t) { var e = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(t); return e ? { r: parseInt(e[1], 16), g: parseInt(e[2], 16), b: parseInt(e[3], 16) } : null }

    function n(t, e, i, o, s, a) { return t >= i && t <= i + s && e >= o && e <= o + a }

    function r(t, e, i) { for (var o = !1, s = 0, a = i.length - 1; s < i.length; a = s++) { var n = i[s][0],
                r = i[s][1],
                l = i[a][0],
                p = i[a][1];
            r > e != p > e && t < (l - n) * (e - r) / (p - r) + n && (o = !o) } return o }

    function l(t, e, i, o, s, a) { return (t - i) * (t - i) / (s * s) + (e - o) * (e - o) / (a * a) <= 1 }

    function p(e, o, s, a) { return e < 0 && (e = 0), o < 0 && (o = 0), e > t(i).width() - s && (e = t(i).width() - s), o > t(i).height() - a && (o = t(i).height() - a), { x: e, y: o } }

    function h(t) { for (var e, i, o = t.length; 0 !== o;) i = Math.floor(Math.random() * o), o -= 1, e = t[o], t[o] = t[i], t[i] = e; return t }

    function d() { return !!/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) }
    var g = o;
    t.imageMapProInitialized = function(t) {}, t.imageMapProEventHighlightedShape = function(t, e) {}, t.imageMapProEventUnhighlightedShape = function(t, e) {}, t.imageMapProEventClickedShape = function(t, e) {}, t.imageMapProEventOpenedTooltip = function(t, e) {}, t.imageMapProEventClosedTooltip = function(t) {}, t.imageMapProHighlightShape = function(e, i) { var o = t('[data-shape-title="' + i + '"]').data("index");
        f[e].highlightedShapeIndex != o && (f[e].highlightedShape && f[e].unhighlightShape(), f[e].manuallyHighlightedShape = !0, f[e].highlightShape(o, !1)) }, t.imageMapProUnhighlightShape = function(t) { f[t].highlightedShape && f[t].unhighlightShape() }, t.imageMapProOpenTooltip = function(e, i) { var o = t('[data-shape-title="' + i + '"]').data("index");
        f[e].manuallyShownTooltip = !0, f[e].showTooltip(o), f[e].updateTooltipPosition(o) }, t.imageMapProHideTooltip = function(t) { f[t].hideTooltip() }, t.imageMapProReInitMap = function(t) { f[t].init() }, t.imageMapProIsMobile = function() { return d() };
    var c = t.imageMapProEditorDefaults,
        u = t.imageMapProShapeDefaults,
        f = new Array;
    MutationObserver = e.MutationObserver || e.WebKitMutationObserver;
    var m;
    t.extend(s.prototype, {
        init: function() { var i = this;
            i.parseSettings(), f[this.settings.general.name] = this, this.id = 100 * Math.random(); for (var o = 0; o < i.settings.spots.length; o++) { var s = i.settings.spots[o],
                    a = t.extend(!0, {}, u);
                s = t.extend(!0, a, s), i.settings.spots[o] = t.extend(!0, {}, s), i.settings.spots[o].title && 0 != i.settings.spots[o].title.length || (i.settings.spots[o].title = i.settings.spots[o].id) } i.root.addClass("imp-initialized"), i.root.attr("data-image-map-pro-id", i.settings.id), i.root.html('<div class="imp-wrap niels3"></div>'), i.wrap = i.root.find(".imp-wrap"); var n = new Image;
            n.src = i.settings.image.url, i.loadImage(n, function() {}, function() { var e = "";
                e += '<img src="' + i.settings.image.url + '">', i.wrap.html(e), i.centerImageMap(), i.adjustSize(), i.drawShapes(), i.addTooltips(), i.initFullscreen(), i.events(), i.animateShapesLoop(), t.imageMapProInitialized(i.settings.general.name) }), t(e).on("resize", function() { i.visibleTooltip && i.updateTooltipPosition(i.highlightedShapeIndex) }) },
        parseSettings: function() { this.settings.general.image_url && (this.settings.image.url = this.settings.general.image_url) },
        loadImage: function(e, i, s) { e.complete && e.naturalWidth !== o && e.naturalHeight !== o ? s() : (i(), t(e).on("load", function() { t(e).off("load"), s() })) },
        centerImageMap: function() { var t = this;
            1 == parseInt(t.settings.general.center_image_map, 10) && t.wrap.css({ margin: "0 auto" }) },
        adjustSize: function() { var i = this; if (1 == parseInt(i.settings.runtime.is_fullscreen, 10)) { var o = t(e).width() / t(e).height(),
                    s = i.settings.general.width / i.settings.general.height; return s < o ? (i.settings.general.width = t(e).height() * s, i.settings.general.height = t(e).height()) : (i.settings.general.width = t(e).width(), i.settings.general.height = t(e).width() / s), void i.wrap.css({ width: i.settings.general.width, height: i.settings.general.height }) } if (1 == parseInt(i.settings.general.responsive, 10)) { if (1 == parseInt(i.settings.general.preserve_quality, 10)) { i.settings.general.naturalWidth || i.settings.general.width;
                    i.wrap.css({ "max-width": i.settings.general.naturalWidth }) } } else i.wrap.css({ width: i.settings.general.width, height: i.settings.general.height }) },
        drawShapes: function() { for (var t = this, e = 0; e < t.settings.spots.length; e++) { var i = t.settings.spots[e]; if (i.x = parseFloat(i.x), i.y = parseFloat(i.y), i.width = parseFloat(i.width), i.height = parseFloat(i.height), i.default_style.stroke_width = parseInt(i.default_style.stroke_width), i.mouseover_style.stroke_width = parseInt(i.mouseover_style.stroke_width), "poly" == i.type)
                    for (var o = 0; o < i.points.length; o++) i.points[o].x = parseFloat(i.points[o].x), i.points[o].y = parseFloat(i.points[o].y) } t.settings.general.width = parseInt(t.settings.general.width), t.settings.general.height = parseInt(t.settings.general.height), t.wrap.prepend('<div class="imp-shape-container"></div>'), t.shapeContainer = t.wrap.find(".imp-shape-container"); var s = "",
                n = !1,
                r = t.settings.general.width,
                l = t.settings.general.height;
            1 == parseInt(t.settings.general.responsive, 10) && (r = t.settings.general.naturalWidth, l = t.settings.general.naturalHeight); for (var p = '<svg class="hs-poly-svg" viewBox="0 0 ' + r + " " + l + '" preserveAspectRatio="none">', e = 0; e < t.settings.spots.length; e++) { var i = t.settings.spots[e]; if ("spot" == i.type)
                    if (1 == parseInt(i.default_style.use_icon, 10)) { var h = "",
                            d = i.width < 44 ? 44 : i.width,
                            g = i.height < 44 ? 44 : i.height;
                        h += "left: " + i.x + "%;", h += "top: " + i.y + "%;", h += "width: " + d + "px;", h += "height: " + g + "px;"; var c = -g / 2,
                            u = -d / 2; if (1 == parseInt(i.default_style.icon_is_pin, 10) && (c = -g, i.height < 44 && (c = -g / 2 - i.height / 2)), h += "margin-left: " + u + "px;", h += "margin-top: " + c + "px;", h += "background-image: url(" + i.default_style.icon_url + ")", h += "background-position: center;", h += "background-repeat: no-repeat;", "fade" == t.settings.general.pageload_animation && (h += "opacity: 0;"), "grow" == t.settings.general.pageload_animation && (h += "opacity: " + i.default_style.opacity + ";", h += "transform: scale(0, 0);-moz-transform: scale(0, 0);-webkit-transform: scale(0, 0);", 1 == parseInt(i.default_style.icon_is_pin, 10) && (h += "transform-origin: 50% 100%;-moz-transform-origin: 50% 100%;-webkit-transform-origin: 50% 100%;")), "none" == t.settings.general.pageload_animation && (h += "opacity: " + i.default_style.opacity + ";"), s += '<div class="imp-shape imp-shape-spot" id="' + i.id + '" data-shape-title="' + i.title + '" style="' + h + '" data-index=' + e + ">", "library" == i.default_style.icon_type ? (s += '   <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" viewBox="' + i.default_style.icon_svg_viewbox + '" xml:space="preserve" width="' + i.width + 'px" height="' + i.height + 'px">', s += '       <path style="fill:' + i.default_style.icon_fill + '" d="' + i.default_style.icon_svg_path + '"></path>', s += "   </svg>") : s += '<img src="' + i.default_style.icon_url + '">', 1 == parseInt(i.default_style.icon_shadow, 10)) { var f = "";
                            f += "width: " + i.width + "px;", f += "height: " + i.height + "px;", f += "top: " + i.height / 2 + "px;", s += '<div style="' + f + '" class="imp-shape-icon-shadow"></div>' } s += "</div>" } else { var h = "",
                            m = a(i.default_style.background_color) || { r: 0, b: 0, g: 0 },
                            _ = a(i.default_style.border_color) || { r: 0, b: 0, g: 0 };
                        h += "left: " + i.x + "%;", h += "top: " + i.y + "%;", h += "width: " + i.width + "px;", h += "height: " + i.height + "px;", h += "margin-left: -" + i.width / 2 + "px;", h += "margin-top: -" + i.height / 2 + "px;", h += "border-radius: " + i.default_style.border_radius + "px;", h += "background: rgba(" + m.r + ", " + m.g + ", " + m.b + ", " + i.default_style.background_opacity + ");", h += "border-width: " + i.default_style.border_width + "px;", h += "border-style: " + i.default_style.border_style + ";", h += "border-color: rgba(" + _.r + ", " + _.g + ", " + _.b + ", " + i.default_style.border_opacity + ");", "fade" == t.settings.general.pageload_animation && (h += "opacity: 0;"), "grow" == t.settings.general.pageload_animation && (h += "opacity: " + i.default_style.opacity + ";", h += "transform: scale(0, 0);-moz-transform: scale(0, 0);-webkit-transform: scale(0, 0);"), "none" == t.settings.general.pageload_animation && (h += "opacity: " + i.default_style.opacity + ";"), s += '<div class="imp-shape imp-shape-spot" id="' + i.id + '" data-shape-title="' + i.title + '" style="' + h + '" data-index=' + e + "></div>" }
                if ("rect" == i.type) { var h = "",
                        m = a(i.default_style.background_color) || { r: 0, b: 0, g: 0 },
                        _ = a(i.default_style.border_color) || { r: 0, b: 0, g: 0 };
                    h += "left: " + i.x + "%;", h += "top: " + i.y + "%;", h += "width: " + i.width + "%;", h += "height: " + i.height + "%;", h += "border-radius: " + i.default_style.border_radius + "px;", h += "background: rgba(" + m.r + ", " + m.g + ", " + m.b + ", " + i.default_style.background_opacity + ");", h += "border-width: " + i.default_style.border_width + "px;", h += "border-style: " + i.default_style.border_style + ";", h += "border-color: rgba(" + _.r + ", " + _.g + ", " + _.b + ", " + i.default_style.border_opacity + ");", "fade" == t.settings.general.pageload_animation && (h += "opacity: 0;"), "grow" == t.settings.general.pageload_animation && (h += "opacity: " + i.default_style.opacity + ";", h += "transform: scale(0, 0);-moz-transform: scale(0, 0);-webkit-transform: scale(0, 0);"), "none" == t.settings.general.pageload_animation && (h += "opacity: " + i.default_style.opacity + ";"), s += '<div class="imp-shape imp-shape-rect" id="' + i.id + '" data-shape-title="' + i.title + '" style="' + h + '" data-index=' + e + "></div>" } if ("oval" == i.type) { var h = "",
                        m = a(i.default_style.background_color) || { r: 0, b: 0, g: 0 },
                        _ = a(i.default_style.border_color) || { r: 0, b: 0, g: 0 };
                    h += "left: " + i.x + "%;", h += "top: " + i.y + "%;", h += "width: " + i.width + "%;", h += "height: " + i.height + "%;", h += "border-radius: 50% 50%;", h += "background: rgba(" + m.r + ", " + m.g + ", " + m.b + ", " + i.default_style.background_opacity + ");", h += "border-width: " + i.default_style.border_width + "px;", h += "border-style: " + i.default_style.border_style + ";", h += "border-color: rgba(" + _.r + ", " + _.g + ", " + _.b + ", " + i.default_style.border_opacity + ");", "fade" == t.settings.general.pageload_animation && (h += "opacity: 0;"), "grow" == t.settings.general.pageload_animation && (h += "opacity: " + i.default_style.opacity + ";", h += "transform: scale(0, 0);-moz-transform: scale(0, 0);-webkit-transform: scale(0, 0);"), "none" == t.settings.general.pageload_animation && (h += "opacity: " + i.default_style.opacity + ";"), s += '<div class="imp-shape imp-shape-oval" id="' + i.id + '" data-shape-title="' + i.title + '" style="' + h + '" data-index=' + e + "></div>" } if ("poly" == i.type) { n = !0; var y = a(i.default_style.fill) || { r: 0, b: 0, g: 0 },
                        b = a(i.default_style.stroke_color) || { r: 0, b: 0, g: 0 },
                        v = ""; if (v += "width: 100%;", v += "height: 100%;", v += "fill: rgba(" + y.r + ", " + y.g + ", " + y.b + ", " + i.default_style.fill_opacity + ");", v += "stroke: rgba(" + b.r + ", " + b.g + ", " + b.b + ", " + i.default_style.stroke_opacity + ");", v += "stroke-width: " + i.default_style.stroke_width + "px;", v += "stroke-dasharray: " + i.default_style.stroke_dasharray + ";", v += "stroke-linecap: " + i.default_style.stroke_linecap + ";", "fade" == t.settings.general.pageload_animation && (v += "opacity: 0;"), "grow" == t.settings.general.pageload_animation) { v += "opacity: " + i.default_style.opacity + ";", v += "transform: scale(0, 0);-moz-transform: scale(0, 0);-webkit-transform: scale(0, 0);"; var w = i.x + i.width / 2,
                            x = i.y + i.height / 2;
                        v += "transform-origin: " + w + "% " + x + "%;-moz-transform-origin: " + w + "% " + x + "%;-webkit-transform-origin: " + w + "% " + x + "%;" } "none" == t.settings.general.pageload_animation && (v += "opacity: " + i.default_style.opacity + ";"); var k = r * (i.width / 100),
                        S = l * (i.height / 100);
                    p += '           <polygon class="imp-shape imp-shape-poly" style="' + v + '" data-index=' + e + ' id="' + i.id + '" data-shape-title="' + i.title + '" points="', i.vs = new Array; for (var o = 0; o < i.points.length; o++) { var I = r * (i.x / 100) + i.points[o].x / 100 * k,
                            T = l * (i.y / 100) + i.points[o].y / 100 * S;
                        p += I + "," + T + " ", i.vs.push([I, T]) } p += '           "></polygon>' } } p += "</svg>", n ? t.shapeContainer.html(s + p) : t.shapeContainer.html(s) },
        addTooltips: function() {
            var e = this;
            if ("always" == e.settings.tooltips.fullscreen_tooltips || "mobile-only" == e.settings.tooltips.fullscreen_tooltips && d()) { e.fullscreenTooltipsContainer || (t('.imp-fullscreen-tooltips-container[data-image-map-id="' + e.settings.id + '"]').remove(), t("body").prepend('<div class="imp-fullscreen-tooltips-container" data-image-map-id="' + e.settings.id + '"></div>'), e.fullscreenTooltipsContainer = t('.imp-fullscreen-tooltips-container[data-image-map-id="' + e.settings.id + '"]')); for (var i = "", o = 0; o < e.settings.spots.length; o++) { var s = e.settings.spots[o];
                    s.tooltip_content.plain_text = s.tooltip_content.plain_text.replace(/\n/g, "<br>"); var n = "",
                        r = a(s.tooltip_style.background_color) || { r: 0, b: 0, g: 0 }; if (n += "padding: " + s.tooltip_style.padding + "px;", n += "background: rgba(" + r.r + ", " + r.g + ", " + r.b + ", " + s.tooltip_style.background_opacity + ");", "none" == e.settings.tooltips.tooltip_animation && (n += "opacity: 0;"), "fade" == e.settings.tooltips.tooltip_animation && (n += "opacity: 0;", n += "transition-property: opacity;-moz-transition-property: opacity;-webkit-transition-property: opacity;"), "grow" == e.settings.tooltips.tooltip_animation && (n += "transform: scale(0, 0);-moz-transform: scale(0, 0);-webkit-transform: scale(0, 0);", n += "transition-property: transform;-moz-transition-property: -moz-transform;-webkit-transition-property: -webkit-transform;", n += "transform-origin: 50% 50%;-moz-transform-origin: 50% 50%;-webkit-transform-origin: 50% 50%;"), i += '<div class="imp-fullscreen-tooltip" style="' + n + '" data-index="' + o + '">', i += '   <div class="imp-tooltip-close-button" data-index="' + o + '"><i class="fa fa-times" aria-hidden="true"></i></div>', "plain-text" == s.tooltip_content.content_type) { var n = "";
                        n += "color: " + s.tooltip_content.plain_text_color + ";", i += '<div class="imp-tooltip-plain-text" style="' + n + '">' + s.tooltip_content.plain_text + "</div>" } else s.tooltip_content.squares_json ? i += t.squaresRendererRenderObject(s.tooltip_content.squares_json) : i += t.squaresRendererRenderObject(s.tooltip_content.squares_settings);
                    i += "</div>" } e.fullscreenTooltipsContainer.html(i) } else {
                for (var i = "", o = 0; o < e.settings.spots.length; o++) {
                    var s = e.settings.spots[o];
                    s.tooltip_content.plain_text = s.tooltip_content.plain_text.replace(/\n/g, "<br>");
                    var n = "",
                        r = a(s.tooltip_style.background_color) || { r: 0, b: 0, g: 0 },
                        l = "poly" == s.type ? "imp-tooltip-buffer-large" : "";
                    if (n += "border-radius: " + s.tooltip_style.border_radius + "px;", n += "padding: " + s.tooltip_style.padding + "px;", n += "background: rgba(" + r.r + ", " + r.g + ", " + r.b + ", " + s.tooltip_style.background_opacity + ");", "none" == e.settings.tooltips.tooltip_animation && (n += "opacity: 0;"), "fade" == e.settings.tooltips.tooltip_animation && (n += "opacity: 0;", n += "transition-property: opacity;-moz-transition-property: opacity;-webkit-transition-property: opacity;"),
                        "grow" == e.settings.tooltips.tooltip_animation && (n += "transform: scale(0, 0);-moz-transform: scale(0, 0);-webkit-transform: scale(0, 0);", n += "transition-property: transform;-moz-transition-property: -moz-transform;-webkit-transition-property: -webkit-transform;", "top" == s.tooltip_style.position && (n += "transform-origin: 50% 100%;-moz-transform-origin: 50% 100%;-webkit-transform-origin: 50% 100%;"), "bottom" == s.tooltip_style.position && (n += "transform-origin: 50% 0%;-moz-transform-origin: 50% 0%;-webkit-transform-origin: 50% 0%;"), "left" == s.tooltip_style.position && (n += "transform-origin: 100% 50%;-moz-transform-origin: 100% 50%;-webkit-transform-origin: 100% 50%;"), "right" == s.tooltip_style.position && (n += "transform-origin: 0% 50%;-moz-transform-origin: 0% 50%;-webkit-transform-origin: 0% 50%;")), i += '<div class="imp-tooltip" style="' + n + '" data-index="' + o + '">', "top" == s.tooltip_style.position && (i += '   <div class="hs-arrow hs-arrow-bottom" style="border-top-color: rgba(' + r.r + ", " + r.g + ", " + r.b + ", " + s.tooltip_style.background_opacity + ');"></div>', 0 == parseInt(e.settings.tooltips.sticky_tooltips, 10) && (i += '   <div class="imp-tooltip-buffer imp-tooltip-buffer-bottom ' + l + '"></div>')), "bottom" == s.tooltip_style.position && (i += '   <div class="hs-arrow hs-arrow-top" style="border-bottom-color: rgba(' + r.r + ", " + r.g + ", " + r.b + ", " + s.tooltip_style.background_opacity + ');"></div>', 0 == parseInt(e.settings.tooltips.sticky_tooltips, 10) && (i += '   <div class="imp-tooltip-buffer imp-tooltip-buffer-top ' + l + '"></div>')), "left" == s.tooltip_style.position && (i += '   <div class="hs-arrow hs-arrow-right" style="border-left-color: rgba(' + r.r + ", " + r.g + ", " + r.b + ", " + s.tooltip_style.background_opacity + ');"></div>', 0 == parseInt(e.settings.tooltips.sticky_tooltips, 10) && (i += '   <div class="imp-tooltip-buffer imp-tooltip-buffer-right ' + l + '"></div>')), "right" == s.tooltip_style.position && (i += '   <div class="hs-arrow hs-arrow-left" style="border-right-color: rgba(' + r.r + ", " + r.g + ", " + r.b + ", " + s.tooltip_style.background_opacity + ');"></div>', 0 == parseInt(e.settings.tooltips.sticky_tooltips, 10) && (i += '   <div class="imp-tooltip-buffer imp-tooltip-buffer-left ' + l + '"></div>')), "plain-text" == s.tooltip_content.content_type) { var n = "";
                        n += "color: " + s.tooltip_content.plain_text_color + ";", i += '<div class="imp-tooltip-plain-text" style="' + n + '">' + s.tooltip_content.plain_text + "</div>" } else s.tooltip_content.squares_json ? i += t.squaresRendererRenderObject(s.tooltip_content.squares_json) : i += t.squaresRendererRenderObject(s.tooltip_content.squares_settings);
                    i += "</div>"
                }
                e.wrap.prepend(i)
            }
        },
        initFullscreen: function() { var t = this; if (1 == parseInt(t.settings.fullscreen.enable_fullscreen_mode, 10)) { var e = "";
                e += "background: " + t.settings.fullscreen.fullscreen_button_color + "; ", e += "color: " + t.settings.fullscreen.fullscreen_button_text_color + "; "; var i = '<i class="fa fa-arrows-alt" aria-hidden="true"></i>';
                1 == parseInt(t.settings.runtime.is_fullscreen, 10) && (i = '<i class="fa fa-times" aria-hidden="true"></i>'); var o = "Go Fullscreen";
                1 == parseInt(t.settings.runtime.is_fullscreen, 10) && (o = "Close Fullscreen"); var s = ""; "icon" == t.settings.fullscreen.fullscreen_button_type && (s += i), "text" == t.settings.fullscreen.fullscreen_button_type && (s += o), "icon_and_text" == t.settings.fullscreen.fullscreen_button_type && (s += i + " " + o); var a = ""; "icon" == t.settings.fullscreen.fullscreen_button_type && (a += "imp-fullscreen-button-icon-only"); var n = "";
                n += '<div style="' + e + '" class="' + a + " imp-fullscreen-button imp-fullscreen-button-position-" + t.settings.fullscreen.fullscreen_button_position + '">', n += s, n += "</div>", t.wrap.append('<div class="imp-ui"></div>'), t.ui = t.wrap.find(".imp-ui"), t.ui.append(n); var r = t.ui.find(".imp-fullscreen-button");
                1 != parseInt(t.settings.fullscreen.fullscreen_button_position, 10) && 4 != parseInt(t.settings.fullscreen.fullscreen_button_position, 10) || r.css({ "margin-left": -r.outerWidth() / 2 }), 1 == parseInt(t.settings.fullscreen.start_in_fullscreen_mode, 10) && 0 == t.settings.runtime.is_fullscreen && t.toggleFullscreen() } },
        measureTooltipSize: function(t) { if (!("always" == this.settings.tooltips.fullscreen_tooltips || "mobile" == this.settings.tooltips.fullscreen_tooltips && d())) { var e = this.settings.spots[t],
                    i = this.wrap.find('.imp-tooltip[data-index="' + t + '"]');
                0 == parseInt(e.tooltip_style.auto_width, 10) && i.css({ width: e.tooltip_style.width }), i.data("imp-measured-width", i.outerWidth()), i.data("imp-measured-height", i.outerHeight()) } },
        animateShapesLoop: function() { if ("none" != this.settings.general.pageload_animation)
                for (var t = 750 / this.settings.spots.length, e = h(this.settings.spots.slice()), i = 0; i < e.length; i++) this.animateShape(e[i], t * i) },
        animateShape: function(e, i) { var o = this,
                s = t("#" + e.id);
            setTimeout(function() { "fade" == o.settings.general.pageload_animation && s.css({ opacity: e.default_style.opacity }), "grow" == o.settings.general.pageload_animation && s.css({ transform: "scale(1, 1)", "-moz-transform": "scale(1, 1)", "-webkit-transform": "scale(1, 1)" }) }, i) },
        events: function() { var e = this;
            this.wrap.off("mousemove"), this.wrap.on("mousemove", function(t) { e.touch || e.handleEventMove(t) }), this.wrap.off("mouseup"), this.wrap.on("mouseup", function(t) { e.touch || e.handleEventEnd(t) }), this.wrap.off("touchstart"), this.wrap.on("touchstart", function(t) { e.touch = !0, e.handleEventMove(t) }), this.wrap.off("touchmove"), this.wrap.on("touchmove", function(t) { e.handleEventMove(t) }), this.wrap.off("touchend"), this.wrap.on("touchend", function(t) { e.handleEventEnd(t) }), t(i).off("mousemove." + this.settings.id), t(i).on("mousemove." + this.settings.id, function(i) { e.touch || e.manuallyHighlightedShape || e.manuallyShownTooltip || 0 == t(i.target).closest(".imp-wrap niels").length && 0 == t(i.target).closest(".imp-fullscreen-tooltips-container").length && (e.visibleTooltip && e.hideTooltip(), e.clickedShape && e.unclickShape(), e.highlightedShape && e.unhighlightShape()) }), t(i).off("touchstart." + this.settings.id), t(i).on("touchstart." + this.settings.id, function(i) { e.manuallyHighlightedShape || e.manuallyShownTooltip || 0 == t(i.target).closest(".imp-wrap niels2").length && 0 == t(i.target).closest(".imp-fullscreen-tooltips-container").length && (e.visibleTooltip && e.hideTooltip(), e.clickedShape && e.unclickShape(), e.highlightedShape && e.unhighlightShape()) }), t(i).off("click." + this.settings.id, ".imp-tooltip-close-button"), t(i).on("click." + this.settings.id, ".imp-tooltip-close-button", function() { e.hideTooltip(), e.clickedShape && e.unclickShape(), e.highlightedShape && e.unhighlightShape() }), 1 == parseInt(this.settings.general.late_initialization, 10) ? m || (m = new MutationObserver(function(i, o) { clearTimeout(e.initTimeout), e.initTimeout = setTimeout(function() { for (var o = 0; o < i.length; o++)
                        if (0 == t(i[o].target).closest(".imp-initialized").length && !t(i[o].target).hasClass("imp-initialized")) { e.init(); break } }, 50) }), m.observe(i, { subtree: !0, attributes: !0 })) : m && (m.disconnect(), m = o), t(i).off("click." + this.settings.id, '[data-image-map-pro-id="' + this.settings.id + '"] .imp-fullscreen-button'), t(i).on("click." + this.settings.id, '[data-image-map-pro-id="' + this.settings.id + '"] .imp-fullscreen-button', function() { e.toggleFullscreen() }), t(i).on("mouseover", "[data-imp-highlight-shape-on-mouseover]", function() { var i = t(this).data("imp-highlight-shape-on-mouseover"),
                    o = t(this).data("imp-image-map-name"); if (!o || o == e.settings.general.name) { var s = t('[data-shape-title="' + i + '"]').data("index");
                    e.manuallyHighlightedShape = !0, e.highlightShape(s, !0) } }), t(i).on("mouseout", "[data-imp-highlight-shape-on-mouseover]", function() { var i = (t(this).data("imp-highlight-shape-on-mouseover"), t(this).data("imp-image-map-name"));
                i && i != e.settings.general.name || e.unhighlightShape() }), t(i).on("click", "[data-imp-highlight-shape-on-click]", function() { var i = t(this).data("imp-highlight-shape-on-click"),
                    o = t(this).data("imp-image-map-name"); if (!o || o == e.settings.general.name) { var s = t('[data-shape-title="' + i + '"]').data("index");
                    e.highlightedShape && e.unhighlightShape(), e.manuallyHighlightedShape = !0, e.highlightShape(s, !0) } }), t(i).on("mouseover", "[data-imp-unhighlight-shape-on-mouseover]", function() { var i = (t(this).data("imp-unhighlight-shape-on-mouseover"), t(this).data("imp-image-map-name"));
                i && i != e.settings.general.name || e.highlightedShape && e.unhighlightShape() }), t(i).on("mouseover", "[data-imp-unhighlight-shape-on-click]", function() { var i = (t(this).data("imp-unhighlight-shape-on-click"), t(this).data("imp-image-map-name"));
                i && i != e.settings.general.name || e.highlightedShape && e.unhighlightShape() }), t(i).on("mouseover", "[data-imp-open-tooltip-on-mouseover]", function() { var i = t(this).data("imp-open-tooltip-on-mouseover"),
                    o = t(this).data("imp-image-map-name"); if (!o || o == e.settings.general.name) { var s = t('[data-shape-title="' + i + '"]').data("index");
                    e.manuallyShownTooltip = !0, e.showTooltip(s), e.updateTooltipPosition(s) } }), t(i).on("mouseout", "[data-imp-open-tooltip-on-mouseover]", function() { var i = (t(this).data("imp-open-tooltip-on-mouseover"), t(this).data("imp-image-map-name"));
                i && i != e.settings.general.name || e.hideTooltip() }), t(i).on("click", "[data-imp-open-tooltip-on-click]", function() { var i = t(this).data("imp-open-tooltip-on-click"),
                    o = t(this).data("imp-image-map-name"); if (!o || o == e.settings.general.name) { var s = t('[data-shape-title="' + i + '"]').data("index");
                    e.manuallyShownTooltip = !0, e.showTooltip(s), e.updateTooltipPosition(s) } }), t(i).on("mouseover", "[data-imp-close-tooltip-on-mouseover]", function() { var i = (t(this).data("imp-close-tooltip-on-mouseover"), t(this).data("imp-image-map-name"));
                i && i != e.settings.general.name || e.hideTooltip() }), t(i).on("click", "[data-imp-close-tooltip-on-click]", function() { var i = (t(this).data("imp-close-tooltip-on-click"), t(this).data("imp-image-map-name"));
                i && i != e.settings.general.name || e.hideTooltip() }), t(i).on("mouseover", "[data-imp-trigger-shape-on-mouseover]", function() { var i = t(this).data("imp-trigger-shape-on-mouseover"),
                    o = t(this).data("imp-image-map-name"); if (!o || o == e.settings.general.name) { var s = t('[data-shape-title="' + i + '"]').data("index");
                    e.manuallyHighlightedShape = !0, e.manuallyShownTooltip = !0, e.highlightShape(s, !0), e.showTooltip(s), e.updateTooltipPosition(s) } }), t(i).on("mouseout", "[data-imp-trigger-shape-on-mouseover]", function() { var i = (t(this).data("imp-trigger-shape-on-mouseover"), t(this).data("imp-image-map-name"));
                i && i != e.settings.general.name || (e.unhighlightShape(), e.hideTooltip()) }), t(i).on("click", "[data-imp-trigger-shape-on-click]", function() { var i = t(this).data("imp-trigger-shape-on-click"),
                    o = t(this).data("imp-image-map-name"); if (!o || o == e.settings.general.name) { var s = t('[data-shape-title="' + i + '"]').data("index");
                    e.highlightedShape && e.unhighlightShape(), e.manuallyHighlightedShape = !0, e.manuallyShownTooltip = !0, e.highlightShape(s, !0), e.showTooltip(s), e.updateTooltipPosition(s) } }), t(i).on("mouseover", "[data-imp-untrigger-shape-on-mouseover]", function() { var i = (t(this).data("imp-untrigger-shape-on-mouseover"), t(this).data("imp-image-map-name"));
                i && i != e.settings.general.name || (e.highlightedShape && e.unhighlightShape(), e.hideTooltip()) }), t(i).on("mouseover", "[data-imp-untrigger-shape-on-click]", function() { var i = (t(this).data("imp-untrigger-shape-on-click"), t(this).data("imp-image-map-name"));
                i && i != e.settings.general.name || (e.highlightedShape && e.unhighlightShape(), e.hideTooltip()) }) },
        disableEvents: function() { this.wrap.off("mousemove"), this.wrap.off("mouseup"), this.wrap.off("touchstart"), this.wrap.off("touchmove"), this.wrap.off("touchend"), t(i).off("mousemove." + this.settings.id), t(i).off("touchstart." + this.settings.id), t(i).off("click." + this.settings.id, ".imp-tooltip-close-button"), t(i).off("click." + this.settings.id, ".imp-fullscreen-button") },
        handleEventMove: function(e) { if (!this.fullscreenTooltipVisible && (0 == t(e.target).closest(".imp-tooltip").length && !t(e.target).hasClass("imp-tooltip") || 0 != parseInt(this.settings.tooltips.sticky_tooltips, 10))) {
                (this.manuallyHighlightedShape || this.manuallyShownTooltip) && (this.manuallyHighlightedShape = !1, this.manuallyShownTooltip = !1); var i = this.getEventRelativeCoordinates(e),
                    o = this.matchShapeToCoords(i); - 1 != o && o != this.highlightedShapeIndex ? (this.highlightedShape && this.unhighlightShape(), this.highlightShape(o, !0)) : -1 == o && this.highlightedShape && this.highlightedShapeIndex != this.clickedShapeIndex && this.unhighlightShape(), this.highlightedShape && this.visibleTooltipIndex != this.highlightedShapeIndex ? "show-tooltip" == this.highlightedShape.actions.mouseover && (this.visibleTooltip && this.hideTooltip(), this.clickedShape && this.unclickShape(), this.showTooltip(this.highlightedShapeIndex), this.updateTooltipPosition(o, e)) : !this.visibleTooltip || this.highlightedShape || this.clickedShape || this.visibleTooltip && this.hideTooltip(), this.visibleTooltip && this.highlightedShape && 1 == parseInt(this.settings.tooltips.sticky_tooltips, 10) && "show-tooltip" == this.highlightedShape.actions.mouseover && this.updateTooltipPosition(this.highlightedShapeIndex, e) } },
        handleEventEnd: function(e) { if ((0 == t(e.target).closest(".imp-tooltip").length || t(e.target).hasClass("imp-tooltip-buffer")) && !this.fullscreenTooltipVisible) {
                (this.manuallyHighlightedShape || this.manuallyShownTooltip) && (this.manuallyHighlightedShape = !1, this.manuallyShownTooltip = !1); var i = this.getEventRelativeCoordinates(e),
                    o = this.matchShapeToCoords(i); - 1 != o && o != this.clickedShapeIndex ? (this.clickedShape && this.unclickShape(), this.clickShape(o, e)) : -1 == o && this.clickedShape && this.unclickShape() } },
        getEventRelativeCoordinates: function(t) { var e, i; if ("touchstart" == t.type || "touchmove" == t.type || "touchend" == t.type || "touchcancel" == t.type) { var o = t.originalEvent.touches[0] || t.originalEvent.changedTouches[0];
                e = o.pageX, i = o.pageY } else "mousedown" != t.type && "mouseup" != t.type && "mousemove" != t.type && "mouseover" != t.type && "mouseout" != t.type && "mouseenter" != t.type && "mouseleave" != t.type || (e = t.pageX, i = t.pageY); return e -= this.wrap.offset().left, i -= this.wrap.offset().top, e = e / this.wrap.width() * 100, i = i / this.wrap.height() * 100, { x: e, y: i } },
        getEventCoordinates: function(t) { var e, i; if ("touchstart" == t.type || "touchmove" == t.type || "touchend" == t.type || "touchcancel" == t.type) { var o = t.originalEvent.touches[0] || t.originalEvent.changedTouches[0];
                e = o.pageX, i = o.pageY } else "mousedown" != t.type && "mouseup" != t.type && "mousemove" != t.type && "mouseover" != t.type && "mouseout" != t.type && "mouseenter" != t.type && "mouseleave" != t.type || (e = t.pageX, i = t.pageY); return { x: e, y: i } },
        matchShapeToCoords: function(t) { for (var e = this.settings.spots.length - 1; e >= 0; e--) { var i = this.settings.spots[e]; if ("poly" == i.type) { var o = t.x / 100 * this.wrap.width(),
                        s = t.y / 100 * this.wrap.height(); if (o = o * this.settings.general.width / this.wrap.width(), s = s * this.settings.general.height / this.wrap.height(), r(o, s, i.vs)) return e } if ("spot" == i.type) { var a = i.width < 44 ? 44 : i.width,
                        p = i.height < 44 ? 44 : i.height,
                        o = t.x / 100 * this.wrap.width(),
                        s = t.y / 100 * this.wrap.height(),
                        h = i.x / 100 * this.wrap.width() - a / 2,
                        d = i.y / 100 * this.wrap.height() - p / 2,
                        g = a,
                        c = p; if (1 == parseInt(i.default_style.icon_is_pin, 10) && 1 == parseInt(i.default_style.use_icon, 10) && (d -= p / 2, i.height < 44 && (d += i.height / 2)), n(o, s, h, d, g, c)) return e } if ("rect" == i.type && n(t.x, t.y, i.x, i.y, i.width, i.height)) return e; if ("oval" == i.type) { var o = t.x,
                        s = t.y,
                        u = i.x + i.width / 2,
                        f = i.y + i.height / 2,
                        h = i.width / 2,
                        d = i.height / 2; if (l(o, s, u, f, h, d)) return e } } return -1 },
        applyMouseoverStyles: function(t) { var e = this,
                i = e.settings.spots[t],
                o = this.wrap.find("#" + i.id),
                s = ""; if ("spot" == i.type && 0 == parseInt(i.default_style.use_icon, 10)) { var n = a(i.mouseover_style.background_color) || { r: 0, b: 0, g: 0 },
                    r = a(i.mouseover_style.border_color) || { r: 0, b: 0, g: 0 };
                s += "left: " + i.x + "%;", s += "top: " + i.y + "%;", s += "width: " + i.width + "px;", s += "height: " + i.height + "px;", s += "margin-left: -" + i.width / 2 + "px;", s += "margin-top: -" + i.height / 2 + "px;", s += "opacity: " + i.mouseover_style.opacity + ";", s += "border-radius: " + i.mouseover_style.border_radius + "px;", s += "background: rgba(" + n.r + ", " + n.g + ", " + n.b + ", " + i.mouseover_style.background_opacity + ");", s += "border-width: " + i.mouseover_style.border_width + "px;", s += "border-style: " + i.mouseover_style.border_style + ";", s += "border-color: rgba(" + r.r + ", " + r.g + ", " + r.b + ", " + i.mouseover_style.border_opacity + ");" } if ("spot" == i.type && 1 == parseInt(i.default_style.use_icon, 10)) { var l = i.width < 44 ? 44 : i.width,
                    p = i.height < 44 ? 44 : i.height;
                s += "left: " + i.x + "%;", s += "top: " + i.y + "%;", s += "width: " + l + "px;", s += "height: " + p + "px;"; var h = -p / 2,
                    d = -l / 2;
                1 == parseInt(i.default_style.icon_is_pin, 10) && (h = -p, i.height < 44 && (h = -p / 2 - i.height / 2)), s += "margin-left: " + d + "px;", s += "margin-top: " + h + "px;", s += "opacity: " + i.mouseover_style.opacity + ";" } if ("spot" == i.type && 1 == parseInt(i.default_style.use_icon, 10) && "library" == i.default_style.icon_type && o.find("path").attr("style", "fill:" + i.mouseover_style.icon_fill), "rect" == i.type) { var n = a(i.mouseover_style.background_color) || { r: 0, b: 0, g: 0 },
                    r = a(i.mouseover_style.border_color) || { r: 0, b: 0, g: 0 };
                s += "left: " + i.x + "%;", s += "top: " + i.y + "%;", s += "width: " + i.width + "%;", s += "height: " + i.height + "%;", s += "opacity: " + i.mouseover_style.opacity + ";", s += "border-radius: " + i.mouseover_style.border_radius + "px;", s += "background: rgba(" + n.r + ", " + n.g + ", " + n.b + ", " + i.mouseover_style.background_opacity + ");", s += "border-width: " + i.mouseover_style.border_width + "px;", s += "border-style: " + i.mouseover_style.border_style + ";", s += "border-color: rgba(" + r.r + ", " + r.g + ", " + r.b + ", " + i.mouseover_style.border_opacity + ");" } if ("oval" == i.type) { var n = a(i.mouseover_style.background_color) || { r: 0, b: 0, g: 0 },
                    r = a(i.mouseover_style.border_color) || { r: 0, b: 0, g: 0 };
                s += "left: " + i.x + "%;", s += "top: " + i.y + "%;", s += "width: " + i.width + "%;", s += "height: " + i.height + "%;", s += "opacity: " + i.mouseover_style.opacity + ";", s += "border-radius: 50% 50%;", s += "background: rgba(" + n.r + ", " + n.g + ", " + n.b + ", " + i.mouseover_style.background_opacity + ");", s += "border-width: " + i.mouseover_style.border_width + "px;", s += "border-style: " + i.mouseover_style.border_style + ";", s += "border-color: rgba(" + r.r + ", " + r.g + ", " + r.b + ", " + i.mouseover_style.border_opacity + ");" } if ("poly" == i.type) { var g = a(i.mouseover_style.fill) || { r: 0, b: 0, g: 0 },
                    c = a(i.mouseover_style.stroke_color) || { r: 0, b: 0, g: 0 };
                s += "opacity: " + i.mouseover_style.opacity + ";", s += "fill: rgba(" + g.r + ", " + g.g + ", " + g.b + ", " + i.mouseover_style.fill_opacity + ");", s += "stroke: rgba(" + c.r + ", " + c.g + ", " + c.b + ", " + i.mouseover_style.stroke_opacity + ");", s += "stroke-width: " + i.mouseover_style.stroke_width + "px;", s += "stroke-dasharray: " + i.mouseover_style.stroke_dasharray + ";", s += "stroke-linecap: " + i.mouseover_style.stroke_linecap + ";" } o.attr("style", s) },
        applyDefaultStyles: function(t) { var e = this,
                i = e.settings.spots[t],
                o = this.wrap.find("#" + i.id),
                s = ""; if ("spot" == i.type && 0 == parseInt(i.default_style.use_icon, 10)) { var n = a(i.default_style.background_color) || { r: 0, b: 0, g: 0 },
                    r = a(i.default_style.border_color) || { r: 0, b: 0, g: 0 };
                s += "left: " + i.x + "%;", s += "top: " + i.y + "%;", s += "width: " + i.width + "px;", s += "height: " + i.height + "px;", s += "margin-left: -" + i.width / 2 + "px;", s += "margin-top: -" + i.height / 2 + "px;", s += "opacity: " + i.default_style.opacity + ";", s += "border-radius: " + i.default_style.border_radius + "px;", s += "background: rgba(" + n.r + ", " + n.g + ", " + n.b + ", " + i.default_style.background_opacity + ");", s += "border-width: " + i.default_style.border_width + "px;", s += "border-style: " + i.default_style.border_style + ";", s += "border-color: rgba(" + r.r + ", " + r.g + ", " + r.b + ", " + i.default_style.border_opacity + ");" } if ("spot" == i.type && 1 == parseInt(i.default_style.use_icon, 10)) { var l = i.width < 44 ? 44 : i.width,
                    p = i.height < 44 ? 44 : i.height;
                s += "left: " + i.x + "%;", s += "top: " + i.y + "%;", s += "width: " + l + "px;", s += "height: " + p + "px;"; var h = -p / 2,
                    d = -l / 2;
                1 == parseInt(i.default_style.icon_is_pin, 10) && (h = -p, i.height < 44 && (h = -p / 2 - i.height / 2)), s += "margin-left: " + d + "px;", s += "margin-top: " + h + "px;", s += "opacity: " + i.default_style.opacity + ";" } if ("spot" == i.type && 1 == parseInt(i.default_style.use_icon, 10) && "library" == i.default_style.icon_type && o.find("path").attr("style", "fill:" + i.default_style.icon_fill), "rect" == i.type) { var n = a(i.default_style.background_color) || { r: 0, b: 0, g: 0 },
                    r = a(i.default_style.border_color) || { r: 0, b: 0, g: 0 };
                s += "left: " + i.x + "%;", s += "top: " + i.y + "%;", s += "width: " + i.width + "%;", s += "height: " + i.height + "%;", s += "opacity: " + i.default_style.opacity + ";", s += "border-radius: " + i.default_style.border_radius + "px;", s += "background: rgba(" + n.r + ", " + n.g + ", " + n.b + ", " + i.default_style.background_opacity + ");", s += "border-width: " + i.default_style.border_width + "px;", s += "border-style: " + i.default_style.border_style + ";", s += "border-color: rgba(" + r.r + ", " + r.g + ", " + r.b + ", " + i.default_style.border_opacity + ");" } if ("oval" == i.type) { var n = a(i.default_style.background_color) || { r: 0, b: 0, g: 0 },
                    r = a(i.default_style.border_color) || { r: 0, b: 0, g: 0 };
                s += "left: " + i.x + "%;", s += "top: " + i.y + "%;", s += "width: " + i.width + "%;", s += "height: " + i.height + "%;", s += "opacity: " + i.default_style.opacity + ";", s += "border-radius: 50% 50%;", s += "background: rgba(" + n.r + ", " + n.g + ", " + n.b + ", " + i.default_style.background_opacity + ");", s += "border-width: " + i.default_style.border_width + "px;", s += "border-style: " + i.default_style.border_style + ";", s += "border-color: rgba(" + r.r + ", " + r.g + ", " + r.b + ", " + i.default_style.border_opacity + ");" } if ("poly" == i.type) { var g = a(i.default_style.fill) || { r: 0, b: 0, g: 0 },
                    c = a(i.default_style.stroke_color) || { r: 0, b: 0, g: 0 };
                s += "opacity: " + i.default_style.opacity + ";", s += "fill: rgba(" + g.r + ", " + g.g + ", " + g.b + ", " + i.default_style.fill_opacity + ");", s += "stroke: rgba(" + c.r + ", " + c.g + ", " + c.b + ", " + i.default_style.stroke_opacity + ");", s += "stroke-width: " + i.default_style.stroke_width + "px;", s += "stroke-dasharray: " + i.default_style.stroke_dasharray + ";", s += "stroke-linecap: " + i.default_style.stroke_linecap + ";" } o.attr("style", s) },
        highlightShape: function(e, i) { this.applyMouseoverStyles(e), this.highlightedShapeIndex = e, this.highlightedShape = this.settings.spots[e], i && t.imageMapProEventHighlightedShape(this.settings.general.name, this.highlightedShape.title) },
        unhighlightShape: function() { this.applyDefaultStyles(this.highlightedShapeIndex), t.imageMapProEventUnhighlightedShape(this.settings.general.name, this.highlightedShape.title), this.highlightedShapeIndex = o, this.highlightedShape = o },
        clickShape: function(e, i) { "show-tooltip" == this.settings.spots[e].actions.click && (this.applyMouseoverStyles(e), this.showTooltip(e), this.updateTooltipPosition(e, i), this.clickedShapeIndex = e, this.clickedShape = this.settings.spots[e]), "follow-link" == this.settings.spots[e].actions.click && (0 == t("#imp-temp-link").length && t("body").append('<a href="" id="imp-temp-link" target="_blank"></a>'), t("#imp-temp-link").attr("href", this.settings.spots[e].actions.link), 1 == parseInt(this.settings.spots[e].actions.open_link_in_new_window, 10) ? t("#imp-temp-link").attr("target", "_blank") : t("#imp-temp-link").removeAttr("target"), t("#imp-temp-link")[0].click()), t.imageMapProEventClickedShape(this.settings.general.name, this.settings.spots[e].title) },
        unclickShape: function() { this.applyDefaultStyles(this.clickedShapeIndex), "show-tooltip" == this.clickedShape.actions.click && this.hideTooltip(), this.clickedShapeIndex = o, this.clickedShape = o },
        showTooltip: function(e) { if ("mobile-only" == this.settings.tooltips.fullscreen_tooltips && d() || "always" == this.settings.tooltips.fullscreen_tooltips) { this.visibleTooltip = t('.imp-fullscreen-tooltip[data-index="' + e + '"]'), this.visibleTooltipIndex = e, this.fullscreenTooltipsContainer.show(); var i = this;
                setTimeout(function() { i.visibleTooltip.addClass("imp-tooltip-visible") }, 20), this.fullscreenTooltipVisible = !0, this.bodyOverflow = t("body").css("overflow"), t("body").css({ overflow: "hidden" }) } else t(".imp-tooltip-visible").removeClass("imp-tooltip-visible"), this.visibleTooltip = this.wrap.find('.imp-tooltip[data-index="' + e + '"]'), this.visibleTooltipIndex = e, this.visibleTooltip.addClass("imp-tooltip-visible"), this.measureTooltipSize(e);
            t.imageMapProEventOpenedTooltip(this.settings.general.name, this.settings.spots[e].title) },
        hideTooltip: function() { if (t(".imp-tooltip-visible").removeClass("imp-tooltip-visible"), this.visibleTooltip = o, this.visibleTooltipIndex = o, "mobile-only" == this.settings.tooltips.fullscreen_tooltips && d() || "always" == this.settings.tooltips.fullscreen_tooltips) { var e = this;
                setTimeout(function() { e.fullscreenTooltipsContainer.hide() }, 200), this.fullscreenTooltipVisible = !1, t("body").css({ overflow: this.bodyOverflow }) } t.imageMapProEventClosedTooltip(this.settings.general.name) },
        updateTooltipPosition: function(i, o) { if (!this.fullscreenTooltipVisible) { var s, a, n, r, l, h, d, g, c, u; if (s = this.visibleTooltip, a = this.visibleTooltip.data("imp-measured-width"), n = this.visibleTooltip.data("imp-measured-height"), u = this.settings.spots[i], 1 == parseInt(this.settings.tooltips.sticky_tooltips, 10) && "show-tooltip" == u.actions.mouseover && o) { var f = this.getEventCoordinates(o);
                    g = f.x, c = f.y, r = g - this.wrap.offset().left, l = c - this.wrap.offset().top, h = 0, d = 0 } else "spot" == u.type ? (h = u.width, d = u.height, r = Math.round(10 * u.x) / 10 / 100 * this.wrap.width() - h / 2, l = Math.round(10 * u.y) / 10 / 100 * this.wrap.height() - d / 2) : (h = u.width / 100 * this.wrap.width(), d = u.height / 100 * this.wrap.height(), r = Math.round(10 * u.x) / 10 / 100 * this.wrap.width(), l = Math.round(10 * u.y) / 10 / 100 * this.wrap.height()); var m, _; "left" == u.tooltip_style.position && (m = r - a - 20, _ = l + d / 2 - n / 2), "right" == u.tooltip_style.position && (m = r + h + 20, _ = l + d / 2 - n / 2), "top" == u.tooltip_style.position && (m = r + h / 2 - a / 2, _ = l - n - 20), "bottom" == u.tooltip_style.position && (m = r + h / 2 - a / 2, _ = l + d + 20), "spot" == u.type && 1 == parseInt(u.default_style.icon_is_pin, 10) && "spot" == u.type && 1 == parseInt(u.default_style.use_icon, 10) && (_ -= d / 2); var y = { x: m, y: _ }; if (1 == parseInt(this.settings.tooltips.constrain_tooltips, 10)) { var b = this.wrap.offset().left - t(e).scrollLeft(),
                        v = this.wrap.offset().top - t(e).scrollTop();
                    y = p(m + b, _ + v, a, n), y.x -= b, y.y -= v } s.css({ left: y.x, top: y.y }) } },
        toggleFullscreen: function() { if (0 == parseInt(this.settings.runtime.is_fullscreen, 10)) { t("body").addClass("imp-fullscreen-mode"); var e = t.extend(!0, {}, this.settings);
                e.runtime.is_fullscreen = 1, e.id = "999999", e.general.responsive = 0; var i = "";
                i += "background: " + this.settings.fullscreen.fullscreen_background, t("body").append('<div id="imp-fullscreen-wrap" style="' + i + '"><div id="image-map-pro-' + e.id + '"></div></div>'), t("#image-map-pro-" + e.id).imageMapPro(e), this.disableEvents(), g = this } else t("body").removeClass("imp-fullscreen-mode"), t("#imp-fullscreen-wrap").remove(), this.disableEvents(), g.events() }
    }), t.fn.imageMapPro = function(e) { return this.each(function() { t.data(this, "plugin_imageMapPro", new s(this, e)) }) }
}(jQuery, window, document);