// <auto-generated/> - StyleCop hack to not enforce enum value commentation in this file.
namespace Merchello.Core.Acquired.Logging
{
    using System;

    using Merchello.Core.Logging;

    /// <summary>
    /// A profiler that outputs its results to an ILogger
    /// </summary>
    internal class LogProfiler : IProfiler
    {
        private readonly ILogger _logger;

        public LogProfiler(ILogger logger)
        {
            this._logger = logger;
        }

        public string Render()
        {
            return string.Empty;
        }

        public IDisposable Step(string name)
        {
            this._logger.Debug(typeof(LogProfiler), "Starting - " + name);
            return new DisposableTimer(l => this._logger.Info(typeof(LogProfiler), () => name + " (took " + l + "ms)"));
        }

        public void Start()
        {
            //the log will alwasy be started   
        }

        public void Stop(bool discardResults = false)
        {
            //we don't need to do anything here
        }
    }
}
