// <auto-generated/> - StyleCop hack to not enforce enum value commentation in this file.
namespace Merchello.Core.Acquired
{
    internal interface IScopeContextAdapter
    {
        // ok to get a non-existing key, returns null

        object Get(string key);
        void Set(string key, object value);
        void Clear(string key);
    }
}