// <auto-generated/> - StyleCop hack to not enforce enum value commentation in this file.
namespace Merchello.Core.Acquired.Persistence.Querying
{
    using Merchello.Core.Acquired.Persistence.Mappers;
    using Merchello.Core.Acquired.Persistence.SqlSyntax;

    internal interface IQueryFactory
    {
        IMappingResolver MappingResolver { get; }
        ISqlSyntaxProvider SqlSyntax { get; }
        IQuery<T> Create<T>();
    }
}