// <auto-generated/> - StyleCop hack to not enforce enum value commentation in this file.
namespace Merchello.Core.Acquired.Persistence.Querying
{
    public enum TextColumnType
    {
        NVarchar,
        NText
    }
}