// <auto-generated/> - StyleCop hack to not enforce enum value commentation in this file.
namespace Merchello.Core.Acquired.Persistence.DatabaseModelDefinitions
{
    using System.Collections.Generic;

    internal class ConstraintDefinition
    {
        public ConstraintDefinition(ConstraintType type)
        {
            this.constraintType = type;
        }

        private ConstraintType constraintType;
        public bool IsPrimaryKeyConstraint { get { return ConstraintType.PrimaryKey == this.constraintType; } }
        public bool IsUniqueConstraint { get { return ConstraintType.Unique == this.constraintType; } }
        public bool IsNonUniqueConstraint { get { return ConstraintType.NonUnique == this.constraintType; } }

        public string SchemaName { get; set; }
        public string ConstraintName { get; set; }
        public string TableName { get; set; }
        public ICollection<string> Columns = new HashSet<string>();
    }
}