// <auto-generated/> - StyleCop hack to not enforce enum value commentation in this file.
namespace Merchello.Core.Acquired.Persistence.DatabaseModelDefinitions
{
    public enum ConstraintType
    {
        PrimaryKey,
        Unique,
        NonUnique
    }
}