// <auto-generated/> - StyleCop hack to not enforce enum value commentation in this file.
namespace Merchello.Core.Acquired.Persistence.DatabaseModelDefinitions
{
    using System.Collections.Generic;

    public class DeletionDataDefinition : List<KeyValuePair<string, object>>
    {
    }
}