// <auto-generated/> - StyleCop hack to not enforce enum value commentation in this file.
namespace Merchello.Core.Acquired.Persistence.DatabaseModelDefinitions
{
    using System.Collections.Generic;
    using System.Data;

    internal class ForeignKeyDefinition
    {
        public ForeignKeyDefinition()
        {
            this.ForeignColumns = new List<string>();
            this.PrimaryColumns = new List<string>();
            //Set to None by Default
            this.OnDelete = Rule.None;
            this.OnUpdate = Rule.None;
        }

        public virtual string Name { get; set; }
        public virtual string ForeignTable { get; set; }
        public virtual string ForeignTableSchema { get; set; }
        public virtual string PrimaryTable { get; set; }
        public virtual string PrimaryTableSchema { get; set; }
        public virtual Rule OnDelete { get; set; }
        public virtual Rule OnUpdate { get; set; }
        public virtual ICollection<string> ForeignColumns { get; set; }
        public virtual ICollection<string> PrimaryColumns { get; set; }
    }
}