// <auto-generated/> - StyleCop hack to not enforce enum value commentation in this file.
namespace Merchello.Core.Acquired.Persistence.DatabaseModelDefinitions
{
    internal class IndexColumnDefinition
    {
        public virtual string Name { get; set; }
        public virtual Direction Direction { get; set; }
    }
}