// <auto-generated/> - StyleCop hack to not enforce enum value commentation in this file.
namespace Merchello.Core.Acquired.Persistence.DatabaseModelDefinitions
{
    internal enum SystemMethods
    {
        NewGuid,
        CurrentDateTime,
        //NewSequentialId,
        //CurrentUTCDateTime
    }
}