// <auto-generated/> - StyleCop hack to not enforce enum value commentation in this file.
namespace Merchello.Core.Acquired.Persistence.DatabaseModelDefinitions
{
    using System.Collections.Generic;

    public class TableDefinition
    {
        public TableDefinition()
        {
            this.Columns = new List<ColumnDefinition>();

            this.ForeignKeys = new List<ForeignKeyDefinition>();

            this.Indexes = new List<IndexDefinition>();
        }

        public virtual string Name { get; set; }
        public virtual string SchemaName { get; set; }
        public virtual ICollection<ColumnDefinition> Columns { get; set; }
        public virtual ICollection<ForeignKeyDefinition> ForeignKeys { get; set; }
        public virtual ICollection<IndexDefinition> Indexes { get; set; }
    }
}