// <auto-generated/> - StyleCop hack to not enforce enum value commentation in this file.
namespace Merchello.Core.Acquired.Persistence.Mappers
{
    using System;

    using Merchello.Core.Persistence.Mappers;

    internal interface IMappingResolver
    {
        /// <summary>
        /// Return a mapper by type
        /// </summary>
        /// <param name="type"></param>
        /// <returns></returns>
        BaseMapper ResolveMapperByType(Type type);
    }
}